{% set name = "point-annotator" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f00a852f605124374c6f7b5b732e335a834fe13d18ff77c079fe0fec59fd4ae5

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3
    - pip
    - setuptools >=40.0
    - setuptools_scm
  run:
    - python >=3
    - pandas >=0.24.0
    - numpy
    - scipy

test:
  imports:
    - pointannotator.annotate_samples
    - pointannotator.tests

about:
  home: https://github.com/biolab/point-annotator
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Package for annotating the data (e.g. cell data).'
  description: |
    This package provides functionalities to annotate data with labels based on the Mann-Whitney U test and Hypergeometric test. 
    Currently, we provide examples of the fast annotation of gene expression data with the cell types based on marker genes.
  dev_url: https://github.com/biolab/point-annotator

extra:
  recipe-maintainers:
    - jakakokosar
    - PrimozGodec
