{% set name = "point-annotator" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0bae70fc5aa67e39c230b56a7e10cea46d8fef3a52770721da3d382307fe33ef

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=40.0
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - pandas >=0.24.0
    - numpy
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - pointannotator.annotate_samples
    - pointannotator.tests

about:
  home: https://github.com/biolab/point-annotator
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Package for annotating the data (e.g. cell data).'
  description: |
    This package provides functionalities to annotate data with labels based on the Mann-Whitney U test and Hypergeometric test. 
    Currently, we provide examples of the fast annotation of gene expression data with the cell types based on marker genes.
  dev_url: https://github.com/biolab/point-annotator

extra:
  recipe-maintainers:
    - jakakokosar
    - PrimozGodec
