travis:
  secure:
    BINSTAR_TOKEN: q4oay9SDpMI9a7plbC2YTGUOYIjCktOK93PBZ6OCtsths7NyD3mGkMXHHpZvAbsRQiM3UKpF078QAY0cwlPVw5DVeJbdBlfn21jJoNYjQrqsph2EHlFxv/6GqwZFDevtN6gdwfK4VQHsdikGwd3kbORwanns/UE7NGWG59uTA7B0MxytB1z7yNx83RMvnYawpziwOwbguYPfh0Z7v/p/kJcDjCnJ2rrIq8588T828E7cVAw7uEQDdRwJcixe+Y8UyI9/uFqnAD9Ui8eWGf684aSZO98MyYFzBlMk7zruVCGQ2c3t636KUFoco3IjobuLAcNFMu7HMekQqoASR1pDCgxTVSsSVLX1A0T1xhzHhmI3ReA18IY8lnzr0+EVAWkWQPEak1X5m8Q6VpDf6W+zRXhhBULYkzbo2glvGo/QyExW2/J1NH+ASSyNQn6cm97ezFI4T/E/ylO35V6vsW1czi5MXWyohJvwmCQ/BZ38mNcabnC5Zr9Ua9jL9xDgbQY6L2hyGAr2eFE+v46jiROOPJ/McZwswxfvpmgqwCIwWertUpF4geU5dmSZyo7Vvr/hK9kcGvPsNbfV/m6MfKek2beId+/Q8AA3rU/SzSOBGZvrO921FXRqM/fnFsERann/qG3F3iuCPvGi3t/vTYTD9xwUBuCu9614xlC2GVa7sNI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
