travis:
  secure:
    BINSTAR_TOKEN: NJq59n7AEbEJPgbSkwMwf+fbqUoF2o1m3T2FSWmWflrwFuWKTO8CreWCzFr8Yh3+3QVEOTsGm+EZ4r/9p4WSwem5+sR9+3KsiDtlYCqJCBpmXyLGZW/PMu2K47UhIfp6H5BwsE2KkLgZWdd/Y32490NyN7KwjznDvl6UVeThYZFtyysxir81lNRryjao3aKHdGnt2iSs7584xzKCivCW038pVVChC/PMxYX35QEO8Kn6pEx66HKuWI9GxGlMEPxRzO/WBU73CHOe9wcKFr/VZPyZRqX4K1wGknDQ+aExe2WbM5zBU9keVLvGTZzNIB/E+AhRxFHp877BdnDr0LExRrmuqeGaEggHy28vh74uFewkdAM0crjzYCo7qG9GUWHNPC2uTZqzO5o1bZE9QEhWMgaFNQ0IDgAgYEOc3E4awWoMvCVb3RngsFJOpV80J9ShzbSbXXbRcNcOPyjmw6cfQhi4JDBiPIvhWYSVa3TRnJ18V9LSW8oEFBGcCoNva/Y+nPmg70Y8WytUrRohnWDlgwE7vXaUr/mluk2NEE7lEzvdA0FKlIDxtHQTN5/nSDHXqEoNz8g2Crki+ugdpLf8trTHoz6PJ+phm+SwtzkR4ER69tayRf3R+/OE9Qt8+TomaVZZpj0KxUFP4THjuIjYmn3bSvV5hGdX7nHTptbuETY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
